### ISSUE TITLE
Typescript "Expand" brace style does not put opening brace on own line

### ISSUE THREAD

**Issue by dogfoodsilo4** [Glavin001/atom-beautify#1004]
### Description

"Expand" brace style does not put the opening curly brace on it's own/new line when running beatify on Typescript (_.ts) code.  When running beautify on javascript (_.js) code, the brace is correctly placed on it's own line.

Result of beautify is: -

```
private Foo() {
    return "foo";
}
```
### Expected Results

The beautified code should have looked like:

```
private Foo() 
{
    return "foo";
}
```
### Steps to Reproduce
1. Change Atom Beautify settings to Typescript >> Brace Style >> Expand

```
  "atom-beautify":
    js:
      brace_style: "expand"
    typescript:
      brace_style: "expand"
```
1. Create a .ts file and add a function as above
2. Run beautify command ctrl+alt+B
3. This beautified code does not look right!
