### ISSUE TITLE
CSS/LESS Beautifier sorts properties and could result in bug / unexpected result

### ISSUE THREAD

**Issue by simonwjackson** [Glavin001/atom-beautify#101]
Beautifying this..

``` css
.a {
  .something();

  width: 33px;
}
```

..results in this

``` css
.a {
  width: 33px;
  .something();

}
```

This can cause issues if ".something()" produces a "width" property.
