### ISSUE TITLE
SCSS Convert quotes single doesn't work

### ISSUE THREAD

**Issue by Shinigami92** [Glavin001/atom-beautify#1280]
When I select Convert quotes "single" all my quotes converts to double quotes.
This is annoying because linter-scss-lint marks all my double quotes prefered as single quotes.

**Comment by Shinigami92** [comment]
oh it only works with Pretty Diff, but there is the problem, that only tabs are supported :(

**Comment by prettydiff** [comment]
@Shinigami92 Could you please try at http://prettydiff.com/

The published version of Pretty Diff is a bit newer than the version with Atom Beautify.  I am working to close this gap right now.

**Comment by Shinigami92** [comment]
Ok I'm a bit confused ^^'
At home with windows everything works fine. I will try it again tomorrow at work with linux, maybe the is something wrong with the configuration or version

**Comment by Shinigami92** [comment]
Back at work...

config.cson:
```
"*":
  "atom-beautify":
    scss:
      beautify_on_save: true
      convert_quotes: "single"
      indent_size: 2
      no_lead_zero: true
```

![screenshot01](http://abload.de/img/selection_002bxufg.png)

A second problem I found, was that the `no_lead_zero` doesn't work in @include (or braces?!) (line 290)

At home the indent_size is working fine.

Versions:
atom-beautify: 0.29.13
atom: 1.11.1
