### ISSUE TITLE
wrongly beautified Kivy (KV language) files

### ISSUE THREAD

**Issue by mark-orion** [Glavin001/atom-beautify#1609]
# Description

The results of beautification are not what I expect. Atom-beautify identifies KV language files wrongly as "Python" and breaks the KV formatting rules

# Input Before Beautification

This is what the code looked like before:

```
ScreenManagement:
    Main:
    Setup:

<Main>:
    name: 'main'
    beschriftung: ''
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: 0.8
            canvas:
                Color:
                    rgba: 1,0,0,0.3
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: root.beschriftung
            Button:
                text: 'zum Setup'
                on_release: root.manager.current = 'setup'
        BoxLayout:
            size_hint_y: 0.2
            Label:
                text: root.beschriftung
<Setup>:
    name: 'setup'
    Button:
        text: 'zu Main'
        on_release: root.manager.current = 'main'
```

# Expected Output

atom-beautify should not touch .kv files until file format is officially supported.

# Actual Output

The beautified code actually looked like this:

```
ScreenManagement:
    Main:
    Setup:

<Main >:
    name: 'main'
    beschriftung: ''
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            size_hint_y: 0.8
            canvas:
                Color:
                    rgba: 1, 0, 0, 0.3
                Rectangle:
                    pos: self.pos
                    size: self.size
            Label:
                text: root.beschriftung
            Button:
                text: 'zum Setup'
                on_release: root.manager.current = 'setup'
        BoxLayout:
            size_hint_y: 0.2
            Label:
                text: root.beschriftung
<Setup >:
    name: 'setup'
    Button:
        text: 'zu Main'
        on_release: root.manager.current = 'main'
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/mark-orion/b0855c1191d9f303cfa3975eb6ce26a8

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
