### ISSUE TITLE
Feat Request: Config filetypes like .Yaml, .Toml and .HCL

### ISSUE THREAD

**Issue by GeorgeWL** [Glavin001/atom-beautify#1678]
# Description

Would be nice to have support added, the structure itself is very similar to Json, but tabbing is used to nest instead of moustache trees.

A sample of Yaml

```
# Docker Compose file for running a Ruby on Rails app
version: '2'
services:
  db:
    image: postgres
  web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - "3000:3000"
    depends_on:
      - db
```

A sample of Toml

```
baseurl = "http://yoursite.example.com/"
builddrafts = false
canonifyurls = true

[taxonomies]
  category = "categories"
  tag = "tags"

[params]
  description = "Tesla's Awesome Hugo Site"
  author = "Nikola Tesla"
```

a sample of HCL
```
resource "aws_security_group" "ssh" {
    name        = "ssh"
    description = "Allow all inbound SSH traffic"

    ingress {
        from_port   = 22
        to_port     = 22
        protocol    = "tcp"
        cidr_blocks = ["0.0.0.0/0"]
    }
}
```
# Checklist
I have:
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue

- Not a bug, so other tickboxes don't apply
