### ISSUE TITLE
SCSS with PrettyDiff is mangling sass maps

### ISSUE THREAD

**Issue by JayCarney** [Glavin001/atom-beautify#1688]
# Description

Newlines in sass maps are being removed by PrettyDiff

# Input Before Beautification

This is what the code looked like before:

```scss
$breakpoints: (
  'small'  : '(min-width: 320px)',
  'small_only'  : '(min-width: 320px) and (max-width: 599px)',
  'medium' : '(min-width: 600px)',
  'medium_only' : '(min-width: 600px) and (max-width: 1022px)',
  'large'  : '(min-width: 1023px)',
  'oversize'  : '(min-width: #{$max-width})'
) !default;
```

# Expected Output

The beautified code should have looked like this: (works correctly on prettydiff.com)

```scss
$breakpoints: (
    'small': '(min-width: 320px)',
    'small_only': '(min-width: 320px) and (max-width: 599px)',
    'medium': '(min-width: 600px)',
    'medium_only': '(min-width: 600px) and (max-width: 1022px)',
    'large': '(min-width: 1023px)',
    'oversize': '(min-width: #{$max-width})'
)
!default;
```

# Actual Output

The beautified code actually looked like this:

```scss
$breakpoints: ( 'small' : '(min-width: 320px)', 'small_only' : '(min-width: 320px) and (max-width: 599px)', 'medium' : '(min-width: 600px)', 'medium_only' : '(min-width: 600px) and (max-width: 1022px)', 'large' : '(min-width: 1023px)', 'oversize' : '(min-width: #{$max-width})' ) !default;
```

# Steps to Reproduce

1. Add code to Atom editor
2. Run command `Atom Beautify: Beautify Editor`
3. This beautified code does not look right!

# Debug

Here is a link to the `debug.md` Gist: https://gist.github.com/JayCarney/c2023d619b9baf52632228bc83705d90

# Checklist

I have:
- [x] Tried uninstalling and reinstalling Atom Beautify to ensure it installed properly
- [x] Reloaded (or restarted) Atom to ensure it is not a caching issue
- [x] Searched through existing Atom Beautify Issues at https://github.com/Glavin001/atom-beautify/issues
so I know this is not a duplicate issue
- [x] Filled out the Input, Expected, and Actual sections above or have edited/removed them in a way that fully describes the issue.
- [x] Generated debugging information by executing `Atom Beautify: Help Debug Editor` command in Atom and added link for `debug.md` Gist to this issue
