### ISSUE TITLE
Javascript missing the option 'wrap_attributes_indent_size'

### ISSUE THREAD

**Issue by mhaamann** [Glavin001/atom-beautify#446]
According to js-beautify the option 'wrap_attributes_indent_size' should be available, but it does not seem to work when added to .jsbeautifyrc

I tried adding the following to the file `https://github.com/Glavin001/atom-beautify/blob/master/src/languages/javascript.coffee` thinking I would make a PR.

```
wrap_attributes_indent_size:
      type: 'integer'
      default: 0
      description: "Attributes indentation level"
```

But that does not seem to work. Do i need to compile something, or does it simply not work changing the local files inside `.atom/packages/atom-beautify`?
