### ISSUE TITLE
Doesn't indent @keyframes correctly in SCSS

### ISSUE THREAD

**Issue by AchoArnold** [Glavin001/atom-beautify#500]
Hello

``` scss
@keyframes infinite-spinning {
  from {
    transform: rotate(0deg);
  }
  to {
    transform: rotate(360deg);
  }
}
```

Gets beautified to 

``` css
@keyframes infinite-spinning {
    from {
        transform: rotate(0deg);
    }

to {
        transform: rotate(360deg);
    }
}
```
