### ISSUE TITLE
Less beautify error with Link style states

### ISSUE THREAD

**Issue by nojaf** [Glavin001/atom-beautify#53]
Hi,

I'm using atom 0.119.0 on Windows to format my less file. Whoever the output isn't exactly better at all. Also there is a bug when using statements as &:hover and &:link

``` less
                    a {
                        line-height: @headerHeight;

display: block;
                        padding: 0px 15px;
                        font-size: 16px;
                        button {
                            font-size: 16px;
                        }
                        &:link {
                            color: @white;

text-decoration: none;
                        }
                        &:visited {
                            color: @white;

                        }
                        &:hover {
                            color: @orange;

                        }
                        &.green {
                            color: @green;

&:hover {
                                color: @white;

background-color: @green;

                            }
                        }
```

&:hover and &:link become &:(space)hover and &:(space)link. Which doesn't compile anymore.
