### ISSUE TITLE
SCSS - new lines are added regardless of preference

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#531]
Hi Glavin001,

Love your package. Found a little bug.

Beautifying SCSS files adds new lines between each rule regardless of the preference checkbox "CSS - Newlines between rules". I am currently using Pretty Diff, using CSS Comb does not beautify SCSS at all.

Expected:
```scss
          p {
            color: red;
            strong {
              font-weight: bold;
            }
          }
          .foo {
            position: absolute;
          }
```

Instead I get:
```scss
          p {
            color: red;
            
            strong {
              font-weight: bold;
            }
          }
          
          .foo {
            position: absolute;
          }
```
My current settings:
![screen shot 2015-09-02 at 2 32 50 pm](https://cloud.githubusercontent.com/assets/4415419/9623157/51feeb88-5180-11e5-89aa-b7746f7e5f55.png)

![screen shot 2015-09-02 at 2 32 38 pm](https://cloud.githubusercontent.com/assets/4415419/9623162/5d713e08-5180-11e5-91e7-adf4455707c6.png)

![screen shot 2015-09-02 at 2 34 39 pm](https://cloud.githubusercontent.com/assets/4415419/9623165/65e86156-5180-11e5-84ee-2f177dadb40b.png)

Any ideas? Something I could try?
