### ISSUE TITLE
SCSS - neither Honey Comb nor Pretty Diff behaves as intended

### ISSUE THREAD

**Issue by janwerkhoven** [Glavin001/atom-beautify#557]
Formatting SCSS files creates undesirable effects.

Expected:
```SCSS
header {
  .inner {
    h1 {
      float: left;
      margin: 15px 0 15px -3px;
      img {
        @include transition(all 500ms ease);
        @media (max-width: 400px) {
          width: auto;
          height: 33px;
        }
        nav {
          float: right;
          margin: 10px -10px 0 0;
          @include transition(all 500ms ease);
        }
      }
    }
  }
}
```

What Pretty Diff outputs:
* Merges multiple selectors on to one line and does not respect their hierarchy (see first row)
```SCSS
header {.inner {h1 {
      float: left;
      margin: 15px 0 15px -3px;
      img {
        @include transition(all 500ms ease);
        @media (max-width: 400px) {
          width: auto;
          height: 33px;
        }
        nav {
          float: right;
          margin: 10px -10px 0 0;
          @include transition(all 500ms ease);
        }
      }
    }
  }
}
```

What Honey Comb outputs:
* Does not respect the "indent size"
* Bloats the { } braces on to new rows
* Places random white lines in between rules... (wtf)
```SCSS
header
{
    .inner
    {
        h1
        {
            float: left;

            margin: 15px 0 15px -3px;
            img
            {
                @include transition(all 500ms ease);
                @media (max-width: 400px)
                {
                    width: auto;
                    height: 33px;
                }
                nav
                {
                    float: right;

                    margin: 10px -10px 0 0;

                    @include transition(all 500ms ease);
                }
            }
        }
    }
}
```

Please find the Gist debug log here: https://gist.github.com/janwerkhoven/ff3ccb97d15c67155f82

Love your package!

(except for these 3rd party bugs)
