### ISSUE TITLE
Selector separator newline not working in SCSS

### ISSUE THREAD

**Issue by petrchutny** [Glavin001/atom-beautify#599]
Even if I switch it on/off, I am still getting each selector or a new line like this:

``` css
p,
a,
strong {
  font: 18px 'Roboto', sans-serif;
}
```
