### ISSUE TITLE
Project-level .jsbeautifyrc being overridden by _default

### ISSUE THREAD

**Issue by dhowe** [Glavin001/atom-beautify#908]
.jsbeautifyrc at my project root is as follows, but the values appear to be overwritten by unknown "_default" entries  (see js.indent_size for an example, my 8 is overwritten by 2 in 'Project Options'):

Here is the original [debug log](https://gist.github.com/dhowe/250bffb0f02082a9e1195b1d82300cd6)

```

---
  html:
    brace_style: "collapse"
    indent_char: " "
    indent_scripts: "normal"
    indent_size: 2
    max_preserve_newlines: 1
    preserve_newlines: true
    wrap_line_length: 0
  css:
    indent_char: " "
    indent_size: 2
    preserve_newlines: true
  js:
    indent_size: 8
    indent_char: " "
    indent_level: 0
    indent_with_tabs: false
    preserve_newlines: true
    max_preserve_newlines: 2
    jslint_happy: true
```
